name: TechLang Format & Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format-check:
    name: Check TechLang Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check .tl file formatting
        run: |
          python format_tl.py --check examples/

      - name: Lint .tl files
        run: |
          python format_tl.py --lint examples/
        continue-on-error: true  # Don't fail on linting warnings yet

  format-all-check:
    name: Check All TechLang Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find and check all .tl files
        run: |
          # Find all .tl files in the repository
          find . -name "*.tl" -type f | while read file; do
            echo "Checking $file"
            python format_tl.py --check "$file" || exit 1
          done

      - name: Provide formatting fix hint
        if: failure()
        run: |
          echo "❌ Some .tl files need formatting."
          echo "Run 'python format_tl.py --fix <path>' locally to fix formatting issues."
          exit 1
